name: CI
on:
  push:
  pull_request:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        julia: ['1.10', '1']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.julia }}
      - uses: julia-actions/cache@v2
      - name: Instantiate test environment
        run: julia --project=test -e 'using Pkg; Pkg.develop(path="."); Pkg.instantiate()'
      - name: Test
        run: julia --project=test --check-bounds=yes test/runtests.jl
